'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.3053
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace Apollo.DNN.SkinObjects

    Partial Public Class MLTreeViewMenu

        '''<summary>
        '''tblMain control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tblMain As Global.System.Web.UI.HtmlControls.HtmlTable

        '''<summary>
        '''cellHeader control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cellHeader As Global.System.Web.UI.HtmlControls.HtmlTableCell

        '''<summary>
        '''tblHeader control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tblHeader As Global.System.Web.UI.HtmlControls.HtmlTable

        '''<summary>
        '''lblHeader control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblHeader As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''cellBody control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cellBody As Global.System.Web.UI.HtmlControls.HtmlTableCell
    End Class
End Namespace
