'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.1434
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace Apollo.DNN.Modules.PageLocalization

    Partial Public Class Settings

        '''<summary>
        '''plCheckPermissions control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plCheckPermissions As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''chkCheckPermissions control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkCheckPermissions As Global.System.Web.UI.WebControls.CheckBox
    End Class
End Namespace
